// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240228212310_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rather than look at Muhammad's traits or his moral character for the explanation — in other words, at how Muhammad was — Hayward focused on what Muhammad thought and did while leading in order to ascertain whether his concepts, actions and habits reveal substantial and meaningful insights into the effectiveness of his leadership. Hayward investigated what the earliest extant Arabic sources reveal about Muhammad's capacity and aptitude for leadership in order to make a determination as to whether, and to what degree, Muhammad consciously acted in ways that produced positive results, especially the results he actually sought, during his twenty-three years as a leader.",
                            ImageUrl = "https://www.ijtihad.org/wp-content/uploads/2019/06/Screen-Shot-2019-06-01-at-4.20.19-PM.png",
                            Price = 9.99m,
                            Title = "The Leadership of Muhammad"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nineteen Eighty-Four (also published as 1984) is a dystopian novel and cautionary tale by English writer George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his lifetime. Thematically, it centres on the consequences of totalitarianism, mass surveillance, and repressive regimentation of people and behaviours within society.",
                            ImageUrl = "https://booktriggerwarnings.com/images/1/13/1984.jpg",
                            Price = 7.99m,
                            Title = "Nineteen Eighty-Four"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tafsīr al-Qurʾān al-ʿAẓīm better known as Tafsir Ibn Kathir is the tafsir by Ibn Kathir (died 774 AH/1372 CE). It is one of the most famous Islamic books concerned with the science of interpretation of the Quran.[1] It also includes jurisprudential rulings, and takes care of the hadiths and is famous for being almost devoid of Israʼiliyyat.[1] It is the most followed tafsir by salafist muslims.",
                            ImageUrl = "https://umdatalsalik.files.wordpress.com/2010/12/ibnkathirjuz10.jpg",
                            Price = 11.99m,
                            Title = "Tafsir Ibn Kathir"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
